### ISSUE TITLE
ion-item and ion-list-item

### ISSUE THREAD

**Issue by lholmquist** [ebryn/ember-ionic#8]
what is the difference between these two components,  other than the tagname that is output?

https://github.com/ebryn/ember-ionic/blob/master/app/components/ion-item.js

and 

https://github.com/ebryn/ember-ionic/blob/master/app/components/ion-list-item.js

**Comment by lholmquist** [comment]
looking at the ionic stuff here: http://ionicframework.com/docs/api/directive/ionList/

there seems to be only `ion-list` and `ion-item`

**Comment by ebryn** [comment]
they're identical, arguably `ion-list-item` could be removed, when i started building i expected at `ion-item` would be too generic of a name
